name: "Nanit"
description: "Nanit addon based on adam.stanek/nanit"
version: "0.7.6"
slug: "nanit"
init: false 
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  1935/tcp: 1935
options:
  email: email@address.com
  password: password
  address: 192.168.XX.XX:1935
  mqttbroker: 192.168.XX.XX:1883
  mqttuser: mqttuser
  mqttpassword: mqttpassword
schema:
  email: str
  password: password
  address: str
  mqttbroker: str
  mqttuser: str
  mqttpassword: password