name: "Nanit Add-on"
description: "Nanit addon based on adam.stanek/nanit"
version: "0.7.8"
slug: "nanit-addon"
init: false 
arch:
  - amd64
ports:
  1935/tcp: 1935
options:
  email: email@address.com
  password: password
  address: 192.168.XX.XX:1935
  mqttbroker: 192.168.XX.XX:1883
  mqttuser: mqttuser
  mqttpassword: mqttpassword
schema:
  email: str
  password: password
  address: str
  mqttbroker: str
  mqttuser: str
  mqttpassword: password
image: "siyat/nanit-addon"